spring:
  redis:
    host: localhost
    port: 6379
#    password: your-redis-password
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        test-on-borrow: true