services:
    # MongoDB
    mongodb:
        image: mongo:latest # Use the latest official MongoDB image
        container_name: mongodb_container
        restart: unless-stopped
        ports:
            - "27017:27017" # Map the container's port 27017 to the host's port 27017
        environment:
            # Set environment variables for authentication (recommended)
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: test_database
    # Minio Storage Server
    minio:
        image: minio/minio
        container_name: minio
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=password
            - MINIO_DOMAIN=minio
            - MINIO_REGION_NAME=us-east-1
            - MINIO_REGION=us-east-1
        ports:
            - "9000:9000"
            - "9001:9001"
    # Dremio
    dremio:
        image: dremio/dremio-oss:latest
        ports:
            - 9047:9047
            - 31010:31010
            - 32010:32010
            - 45678:45678
        container_name: dremio
        environment:
            - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist