spring:
   cloud:
      stream:
         kafka:
            binder:
               brokers: localhost
               defaultBrokerPort: 9092
         bindings:
            input:
               destination: one-partition-three-replica
               consumer:
                  autoCommitOffset: false