/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.acme.kafka;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.StreamListener;
import org.springframework.cloud.stream.messaging.Sink;
import org.springframework.messaging.Message;

@SpringBootApplication
@EnableBinding(Sink.class)
public class App {

    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);
    }
    
    @StreamListener(Sink.INPUT)
    public void consume(Message<?> arg) {
    	System.out.println("====> " + arg);
    }
}
