spring:
    main:
        web-application-type: none
        allow-bean-definition-overriding: true
    ai:
        model:
            chat: none
            embedding: none
            image: none
            moderation: none
            ocr: none
            audio:
                speech: none
                transcription: none
        chat:
            client:
                enabled: false