spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        format_sql: true

application:
  zk:
    host: localhost
    port: 2181
  leaderElection:
    nodeId: node-001