spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=4
    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      validation-query: SELECT 1
      max-idle-time: 30m
#    initialization-mode: always
  data:
    r2dbc:
      repositories:
        enabled: true

application:
  database:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=4    
server:
  port: 7080